# Data paths
path: /Users/ymdt/src/dreem_nap/data/
path_to_data: /Users/ymdt/src/dreem_nap/data/DEMULTIPLEXED
firebase_credentials_file: /Users/ymdt/src/dreem_nap/data/credentials_firebase.json
path_to_studies: /Users/ymdt/src/dreem_nap/data/DEMULTIPLEXED/samples.csv

# Data manip 
min_cov_bases: 10

# Plot settings
mpl_rcParams_figure_dpi: 200 # the highest the resolution, the slowest the plotting
mpl_rcParams_figure_figsize: [15,7]
