# Data paths
path_to_data: /Users/ymdt/src/data/Gabe
path_to_studies: /Users/ymdt/src/data/Gabe/studies.csv

# Data manip 
min_cov_bases: 100

# Plot settings
mpl_rcParams_figure_dpi: 100 # the highest the resolution, the slowest the plotting
