# Data paths
path_to_data: /Users/ymdt/src/dreem_nap/data/DEMULTIPLEXED
path_to_studies: /Users/ymdt/src/dreem_nap/data/studies.csv

# Data manip 
min_cov_bases: 100
max_mut_rate_DMS: 0.3

# Plot settings
mpl_rcParams_figure_dpi: 100 # the highest the resolution, the slowest the plotting
mpl_rcParams_figure_figsize: [15,7]
